### ISSUE TITLE
HDP 2.6.5

### ISSUE THREAD

**Issue by giezer** [amarmesic/ambari-hdp-docker#1]
Hello, I'm trying to port the blueprint to hdp 2.6.5 and I'm having a lot of trouble performing such procedure. I can not find where the repository is being mounted to change the version.

Can you help me? I am using ambari 2.6.2 and would like to install hdp 2.6.5, I am not able to "decipher" where the repo secret is.

Thank you.

**Comment by amarmesic** [comment]
Hello,

If you want to change HDP version, I suggest changing the version in [hdp-base/Dockerfile](https://github.com/amarmesic/ambari-hdp-docker/blob/master/hdp-base/Dockerfile#L10-L11) on lines 10 and 11.

Please see docs for [​HDP 2.6 Repositories
](https://docs.hortonworks.com/HDPDocuments/Ambari-2.6.2.0/bk_ambari-installation/content/hdp_26_repositories.html)

Let me know if this works

**Comment by giezer** [comment]
Hello. this was the first change I made. And still repo 2.6.0.3 appears in ambari install. I removed the line that informs the version in Smartsense because it changes when changing the repo. I'm doing validations. anyway thankful.

**Comment by amarmesic** [comment]
Try changing the version of Ambari on line 10 to the latest one (2.6.2.0), rebuild the base image and run docker compose again

**Comment by giezer** [comment]
https://community.hortonworks.com/questions/161819/ambari-blueprints-specify-the-exact-hdp-version-26.html

I think i found the problem. it’s recommended first to register the desired version of HDP using a VDF file

**Comment by giezer** [comment]
Good Morning! Returning to comment that the solution of the link above solves the repo. Includes the command below and after that the ambari executed showing the correct version of hdp. At first the only necessary change in the blueprint and the version of the hst-agent (I believe that leaving the blueprint without the line of the version it also works).

curl -v -k -u admin:admin -H "X-Requested-By:ambari" -X POST http://ambari:8080/api/v1/version_definitions -d '{"VersionDefinition": { "version_url" : "file:/tmp/HDP-2.6.5.0-292.xml" }  }'
